name: Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  bun-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: oven-sh/setup-bun@main
      - run: bun install --frozen-lockfile
      - run: mkdir -p static && echo '[]' > static/movies.json
      - run: bun run check
      - run: bun test
